"""add forecasts and anomalies tables

Revision ID: 12d4cce60853
Revises: 82065e98a0f5
Create Date: 2026-06-06 10:37:22.164153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12d4cce60853'
down_revision: Union[str, None] = '82065e98a0f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anomalies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False, comment='Stock ticker'),
    sa.Column('detected_at', sa.String(length=50), nullable=False, comment='ISO timestamp when anomaly was detected'),
    sa.Column('anomaly_type', sa.String(length=50), nullable=False, comment='price_spike / volume_spike / price_crash'),
    sa.Column('z_score', sa.Float(), nullable=False, comment='Standard deviations from mean — higher = more unusual'),
    sa.Column('actual_value', sa.Float(), nullable=False, comment='The price or volume that was anomalous'),
    sa.Column('expected_value', sa.Float(), nullable=False, comment='The expected normal value'),
    sa.Column('description', sa.String(length=500), nullable=True, comment='Human-readable anomaly description'),
    sa.Column('severity', sa.String(length=20), server_default='medium', nullable=False, comment='low / medium / high — used by Phase 5 alerts'),
    sa.Column('is_alerted', sa.Boolean(), server_default='false', nullable=False, comment='True when Phase 5 has sent an alert for this'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_anomalies_id'), 'anomalies', ['id'], unique=False)
    op.create_index(op.f('ix_anomalies_symbol'), 'anomalies', ['symbol'], unique=False)
    op.create_index('ix_anomaly_symbol_detected', 'anomalies', ['symbol', 'detected_at'], unique=False)
    op.create_table('forecasts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False, comment='Stock ticker symbol'),
    sa.Column('forecast_date', sa.String(length=20), nullable=False, comment='Date being forecast: YYYY-MM-DD'),
    sa.Column('model_type', sa.String(length=20), nullable=False, comment='Model: prophet or xgboost'),
    sa.Column('predicted_price', sa.Float(), nullable=True, comment='Predicted closing price from Prophet'),
    sa.Column('lower_bound', sa.Float(), nullable=True, comment='Lower 80% confidence interval'),
    sa.Column('upper_bound', sa.Float(), nullable=True, comment='Upper 80% confidence interval'),
    sa.Column('direction_signal', sa.Integer(), nullable=True, comment='1=up 0=down — XGBoost direction prediction'),
    sa.Column('confidence', sa.Float(), nullable=True, comment='Model confidence 0.0 to 1.0'),
    sa.Column('mae', sa.Float(), nullable=True, comment='Mean Absolute Error of this model run'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_forecast_symbol_date', 'forecasts', ['symbol', 'forecast_date', 'model_type'], unique=False)
    op.create_index(op.f('ix_forecasts_id'), 'forecasts', ['id'], unique=False)
    op.create_index(op.f('ix_forecasts_symbol'), 'forecasts', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_forecasts_symbol'), table_name='forecasts')
    op.drop_index(op.f('ix_forecasts_id'), table_name='forecasts')
    op.drop_index('ix_forecast_symbol_date', table_name='forecasts')
    op.drop_table('forecasts')
    op.drop_index('ix_anomaly_symbol_detected', table_name='anomalies')
    op.drop_index(op.f('ix_anomalies_symbol'), table_name='anomalies')
    op.drop_index(op.f('ix_anomalies_id'), table_name='anomalies')
    op.drop_table('anomalies')
    # ### end Alembic commands ###
