"""add news_articles and stocktwits_posts tables

Revision ID: 39d86517d52f
Revises: 860fcf038fea
Create Date: 2026-05-31 18:56:01.589908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39d86517d52f'
down_revision: Union[str, None] = '860fcf038fea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news_articles',
    sa.Column('id', sa.Integer(), nullable=False, comment='Auto-incrementing unique row ID'),
    sa.Column('url', sa.String(length=2048), nullable=False, comment='Article URL — primary deduplication key'),
    sa.Column('headline', sa.String(length=1024), nullable=False, comment='Article headline / title'),
    sa.Column('body', sa.Text(), nullable=True, comment='Full article text — used by Phase 3 NLP and Phase 4 RAG'),
    sa.Column('source', sa.String(length=100), nullable=False, comment='Source: newsapi / rss_reuters / rss_yahoo'),
    sa.Column('author', sa.String(length=255), nullable=True, comment='Article author if available'),
    sa.Column('published_at', sa.String(length=100), nullable=True, comment='Publication timestamp from the source'),
    sa.Column('ticker_symbols', sa.String(length=500), nullable=True, comment='Comma-separated tickers: AAPL,MSFT — enriched by Phase 3'),
    sa.Column('sentiment_score', sa.Float(), nullable=True, comment='Sentiment score -1.0 to +1.0 — filled by Phase 3'),
    sa.Column('sentiment_label', sa.String(length=20), nullable=True, comment='positive / negative / neutral — filled by Phase 3'),
    sa.Column('is_embedded', sa.Boolean(), server_default='false', nullable=False, comment='True when Phase 4 has created pgvector embedding'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_news_articles_id'), 'news_articles', ['id'], unique=False)
    op.create_index(op.f('ix_news_articles_ticker_symbols'), 'news_articles', ['ticker_symbols'], unique=False)
    op.create_index(op.f('ix_news_articles_url'), 'news_articles', ['url'], unique=True)
    op.create_index('ix_news_ticker_published', 'news_articles', ['ticker_symbols', 'published_at'], unique=False)
    op.create_table('stocktwits_posts',
    sa.Column('id', sa.Integer(), nullable=False, comment='Auto-incrementing row ID'),
    sa.Column('stocktwits_id', sa.String(length=50), nullable=False, comment='Stocktwits message ID — deduplication key'),
    sa.Column('body', sa.String(length=2048), nullable=True, comment='Post text — Phase 4 embeds this into pgvector'),
    sa.Column('ticker_symbol', sa.String(length=10), nullable=False, comment='Stock this post is about e.g. AAPL'),
    sa.Column('author', sa.String(length=100), nullable=True, comment='Stocktwits username'),
    sa.Column('posted_at', sa.String(length=100), nullable=True, comment='When posted on Stocktwits'),
    sa.Column('sentiment_label', sa.String(length=20), nullable=True, comment="bullish / bearish / None — from the user's own label"),
    sa.Column('sentiment_score', sa.Float(), nullable=True, comment='+1.0 bullish / -1.0 bearish / 0.0 neutral'),
    sa.Column('liked_count', sa.Integer(), nullable=False, comment='Number of likes — used as weight in Phase 3 aggregation'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stocktwits_posts_id'), 'stocktwits_posts', ['id'], unique=False)
    op.create_index(op.f('ix_stocktwits_posts_stocktwits_id'), 'stocktwits_posts', ['stocktwits_id'], unique=True)
    op.create_index(op.f('ix_stocktwits_posts_ticker_symbol'), 'stocktwits_posts', ['ticker_symbol'], unique=False)
    op.create_index('ix_stocktwits_ticker_posted', 'stocktwits_posts', ['ticker_symbol', 'posted_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_stocktwits_ticker_posted', table_name='stocktwits_posts')
    op.drop_index(op.f('ix_stocktwits_posts_ticker_symbol'), table_name='stocktwits_posts')
    op.drop_index(op.f('ix_stocktwits_posts_stocktwits_id'), table_name='stocktwits_posts')
    op.drop_index(op.f('ix_stocktwits_posts_id'), table_name='stocktwits_posts')
    op.drop_table('stocktwits_posts')
    op.drop_index('ix_news_ticker_published', table_name='news_articles')
    op.drop_index(op.f('ix_news_articles_url'), table_name='news_articles')
    op.drop_index(op.f('ix_news_articles_ticker_symbols'), table_name='news_articles')
    op.drop_index(op.f('ix_news_articles_id'), table_name='news_articles')
    op.drop_table('news_articles')
    # ### end Alembic commands ###
