"""add forecasts and anomalies tables

Revision ID: 606cef4b24cf
Revises: 12d4cce60853
Create Date: 2026-06-06 11:06:29.388154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '606cef4b24cf'
down_revision: Union[str, None] = '12d4cce60853'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
