"""add news_articles and stocktwits_posts tables

Revision ID: 82065e98a0f5
Revises: 39d86517d52f
Create Date: 2026-05-31 19:07:03.611562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82065e98a0f5'
down_revision: Union[str, None] = '39d86517d52f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
