"""create stocks table

Revision ID: 860fcf038fea
Revises: 
Create Date: 2026-05-26 09:23:17.663102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '860fcf038fea'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stocks',
    sa.Column('id', sa.Integer(), nullable=False, comment='Auto-incrementing unique identifier'),
    sa.Column('symbol', sa.String(length=10), nullable=False, comment='Stock ticker symbol e.g. AAPL, MSFT'),
    sa.Column('company_name', sa.String(length=255), nullable=False, comment='Full company name e.g. Apple Inc.'),
    sa.Column('sector', sa.String(length=100), nullable=True, comment='Business sector e.g. Technology, Healthcare'),
    sa.Column('industry', sa.String(length=100), nullable=True, comment='Industry within sector e.g. Consumer Electronics'),
    sa.Column('description', sa.Text(), nullable=True, comment='Brief company description'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False, comment='Whether this stock is actively being tracked'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stocks_id'), 'stocks', ['id'], unique=False)
    op.create_index('ix_stocks_sector_active', 'stocks', ['sector', 'is_active'], unique=False)
    op.create_index(op.f('ix_stocks_symbol'), 'stocks', ['symbol'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stocks_symbol'), table_name='stocks')
    op.drop_index('ix_stocks_sector_active', table_name='stocks')
    op.drop_index(op.f('ix_stocks_id'), table_name='stocks')
    op.drop_table('stocks')
    # ### end Alembic commands ###
